name: Test and publish Docker image
on:
  push:
    branches:
      - master
    tags:
      - '**'
jobs:
  call-build-and-test-workflow:
    uses: roland-burke/workflows.git/.github/workflows/build-and-test-go.yml@master

  build-and-push-docker-image:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: myMeta # you'll use this in the next step
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/roland-burke/network-overview
          # Docker tags based on the following events/attributes
          tags: |
            type=semver,pattern={{version}}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm/v7
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.myMeta.outputs.tags }}
          labels: ${{ steps.myMeta.outputs.labels }}
